### ISSUE TITLE
Move files into top level directory from fortune-mod/

### ISSUE THREAD

**Issue by jeffsheltren** [shlomif/fortune-mod#10]
I'm not sure why this repo has a sub directory `fortune-mod` instead of having all of those files at the top level of the repo. It would be cleaner to move all those files to the top level of the repo.

**Comment by shlomif** [comment]
Hi @jeffsheltren !

I prefer to have a sub-dir so I can later on create other sub dirs that won't be part of the main source distro and won't be reachable to cmake / cpack / etc. . For an example of that, see https://github.com/shlomif/fc-solve . Can I close this issue?

**Comment by jeffsheltren** [comment]
As it is now, un-taring a release will give e.g. `fortune-mod-fortune-mod-1.99.5/fortune-mod` which isn't very clean, and definitely isn't standard or what was done in previous "upstream" releases. I'm looking at packaging this for Fedora and think it makes more sense to drop the extra sub-directory. I'm not clear how/why this affects cmake, etc.

**Comment by shlomif** [comment]
Hi Jeff,

On Wed, 28 Jun 2017 20:30:20 +0000 (UTC)
Jeff Sheltren <notifications@github.com> wrote:

> As it is now, un-taring a release will give e.g.
> `fortune-mod-fortune-mod-1.99.5/fortune-mod` which isn't very clean, and
> definitely isn't standard or what was done in previous "upstream" releases.
> I'm looking at packaging this for Fedora and think it makes more sense to
> drop the extra sub-directory. I'm not clear how/why this affects cmake, etc.
> 

you can find the official release tarballs of fortune-mod as prepared by cpack
here:

http://www.shlomifish.org/open-source/projects/fortune-mod/

they have a proper containing directory.

Please don't use github's tags for that.

Regards,

	Shlomi Fish

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Let’s talk about restores instead of backups - http://is.gd/WatQqu

<rindolf> Underscores are the most nutritious punctuation. But you also need
to eat letters, digits and whitespace for a balanced diet.
    — http://is.gd/pHLcFq

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
@jeffsheltren : hi! Did you get my last message? Please reply.

**Comment by shlomif** [comment]
@jeffsheltren : ping.

**Comment by shlomif** [comment]
I'm closing this issue because I think it was addressed in the comments and because @jeffsheltren has been unresponsive for several weeks. If there's need, I will reopen it.
