### ISSUE TITLE
"QFD" in definitions should be in off/definitions

### ISSUE THREAD

**Issue by redblade7** [shlomif/fortune-mod#17]
Hi,

The "definitions" fortune file includes "QFD" which has an "F-word" in it. All the other ones with "the F-word" are in "off/definitions". Was this a mistake on your part?

Thank you!

**Comment by shlomif** [comment]
Hi,

On Wed, 10 Jan 2018 23:57:28 -0800
Red <notifications@github.com> wrote:

> Hi,
> 
> The "definitions" fortune file includes "QFD" which has an "F-word" in it.
> All the other ones with "the F-word" are in "off/definitions". 

thanks for the report. I moved it to "off" to play it safe.

> Was this a
> mistake on your part?
> 

Back when I adopted fortune-mod, see
https://www.reddit.com/r/linux/comments/4dakel/ann_resumed_maintenance_of_linuxs_fortunemod_a/ ,
this issue was already present there. 

-- Shlomi
> Thank you!
> 



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
https://github.com/shlomif/validate-your-html - Validate Your HTML

If at first you don’t succeed, destroy all evidence that you tried.
    — Unknown

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
Resolving as fixed.

**Comment by redblade7** [comment]
OK, thank you! I love fortunes, and in fact have several of my own (see my Github user page)

I should probably mention, this might be a lot of work, but you might want to also check out knghtbrd when you have the time, it is really vulgar. 

There is a discussion thread here: https://forums.gentoo.org/viewtopic-p-8169040.html

**Comment by shlomif** [comment]
On Thu, 11 Jan 2018 14:37:21 +0000 (UTC)
Red <notifications@github.com> wrote:

> OK, thank you! I love fortunes, and in fact have several of my own (see my
> Github user page)
> 
> I should probably mention, this might be a lot of work, but you might want to
> also check out knghtbrd when you have the time, it is really vulgar. 
> 

OK, pull-reqs are welcome.

> There is a discussion thread here:
> https://forums.gentoo.org/viewtopic-p-8169040.html
> 



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
My Photos - http://www.flickr.com/photos/shlomif/

Trust in God, but tie your camel.
    — http://en.wikipedia.org/wiki/God_helps_those_who_help_themselves

Please reply to list if it's a mailing list post - http://shlom.in/reply .
