### ISSUE TITLE
Package is unavailable/broken for CentOS 8

### ISSUE THREAD

**Issue by roysubs** [shlomif/fortune-mod#47]
Just tried to install this on 2x different CentOS minimal installs: `sudo yum install fortune-mod`.

1. CentOS cannot see the package via yum / dnf.

2. On getting the package listed for Fedora (.rpm), I manually try to install it and get into a mess of library conflicts.

Basically, the package is 100% broken for CentOS 8 and not available from the yum / dnf repository.

(Edited to change `apt` to `yum / dnf`)

**Comment by shlomif** [comment]
Hi @roysubs !

> Just tried to install this on 2x different CentOS minimal installs: `sudo apt install fortune-mod`.
> 
>     1. CentOS cannot see the package via apt.
> 
>     2. On getting the package listed for Fedora (.rpm), I manually try to install it and get into a mess of library conflicts.
> 
> 
> Basically, the package is 100% broken for CentOS 8 and not available from the apt repository.

I believe one should use `sudo dnf install forune-mod` (or `sudo yum install forune-mod` ) on CentOS 8/etc.:

* https://www.howtoforge.com/centos-8-package-management-with-dnf-on-the-command-line/

* https://fedoraproject.org/wiki/DNF?rd=Dnf

Also note that you can use `dnf install` on absolute paths or URLs to `*.rpm` files.

**Comment by thejordanclark** [comment]
I think @roysubs just mis-spoke with regards to the "apt" stuff.  It is correct though that fortune-mod is not in the repos for centos 8.  So yum and dnf cannot find the package to install.  It is a annoyance for me as I usually use fortune-mod in my testing within an early deployment pipeline.

**Comment by shlomif** [comment]
Hi @thejordanclark !

> I think @roysubs just mis-spoke with regards to the "apt" stuff. It is correct though that fortune-mod is not in the repos for centos 8. So yum and dnf cannot find the package to install. It is a annoyance for me as I usually use fortune-mod in my testing within an early deployment pipeline.

Thanks for the info and analysis. Seems like you are right based on cursory web searches. I believe someone can set up copr ( https://copr.fedorainfracloud.org/ ) repos with fortune-mod package for centos 8, in order to help the end users resolve the issue. I've only set up one copr repository so far (for unqlite: https://copr.fedorainfracloud.org/coprs/shlomif/unqlite/ ), just to test the waters, so if someone else sets up a fortune-mod copr before I get to it, I can review it and may eventually approve and recommend it. (Case in point: https://en.wikipedia.org/wiki/The_Cathedral_and_the_Bazaar .)

**Comment by shlomif** [comment]
@roysubs : @thejordanclark : hi! According to https://src.fedoraproject.org/rpms/fortune-mod there are [EPEL](https://fedoraproject.org/wiki/EPEL/FAQ) packages for fortune-mod. Did you try them?

**Comment by shlomif** [comment]
@roysubs @thejordanclark : I am closing this ticket to avoid clutter. I can reopen it if needed.
