### ISSUE TITLE
minor typo for Collis Huntington's famous quote

### ISSUE THREAD

**Issue by sflitman** [shlomif/fortune-mod#67]
Whatever is not nailed down is mine.  Whatever I can pry up is not nailed down.
		-- Collis P. **Huntington**, railroad tycoon

**Comment by shlomif** [comment]
On Sun, 03 Jul 2022 19:29:19 -0700
sflitman ***@***.***> wrote:

> Whatever is not nailed down is mine.  Whatever I can pry up is not nailed
> down. -- Collis P. **Huntington**, railroad tycoon
> 
> 

thanks, I'll see.

-- 

Shlomi Fish       https://www.shlomifish.org/
Emma Watson Factoids - https://shlom.in/emwatson-facts

When Chuck Norris receives an E-mail signed “Sent from my iPhone”, he makes
sure that iPhone won’t be able to send any more E-mails — to Norris or
otherwise.
    — https://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by shlomif** [comment]
fixed
