### ISSUE TITLE
Build error with 1.99.5 release

### ISSUE THREAD

**Issue by rezso** [shlomif/fortune-mod#9]
fortune/fortune.c:122:27: fatal error: recode.h: No such file or directory

cmake configure output:

-- The C compiler identification is GNU 6.2.0
-- The CXX compiler identification is GNU 6.2.0
-- Check for working C compiler: /usr/lib/ccache/cc
-- Check for working C compiler: /usr/lib/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib/ccache/c++
-- Check for working CXX compiler: /usr/lib/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Perl: /usr/bin/perl (found version "5.22.2") 
-- Looking for regex.h
-- Looking for regex.h - found
-- Configuring done
-- Generating done

It seems to me, that recode.h not checked at configure time.

**Comment by shlomif** [comment]
On Mon, 22 May 2017 16:28:43 -0700
rezso <notifications@github.com> wrote:

> fortune/fortune.c:122:27: fatal error: recode.h: No such file or directory
> 
> cmake configure output:
> 
> -- The C compiler identification is GNU 6.2.0
> -- The CXX compiler identification is GNU 6.2.0
> -- Check for working C compiler: /usr/lib/ccache/cc
> -- Check for working C compiler: /usr/lib/ccache/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/lib/ccache/c++
> -- Check for working CXX compiler: /usr/lib/ccache/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found Perl: /usr/bin/perl (found version "5.22.2") 
> -- Looking for regex.h
> -- Looking for regex.h - found
> -- Configuring done
> -- Generating done
> 
> It seems to me, that recode.h not checked at configure time.
> 

Hi rezso!

Thanks for the report. Yes, it should be fixed. Note that we are seeking an
alternative to lib-recode because it has some memory leaks and so makes
valgrind fail, and it seems to be undermaintained.

Regards,

	Shlomi Fish


-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Star Trek: “We, the Living Dead” - http://shlom.in/st-wtld

I’m not an actor — I just play one on T.V.
    — http://www.shlomifish.org/humour.html

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
Thanks for the report! I hopefully fixed it in https://github.com/shlomif/fortune-mod/commit/77c4394f12eb745d6262b1eb908918d35155ebf8 and it will be part of the 2.0.0 release (and possibly previous pre-releases). I'm closing this issue for now.
